In [32]:
import pandas as pd
import seaborn as sns

# 데이터프레임의 불린 인덱싱 : DataFrame객체[불린 시리즈]

In [33]:
titanic = sns.load_dataset('titanic')

df = titanic.loc[0:9, ['age', 'fare']]

df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [34]:
df['age'] < 20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [35]:
df[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [36]:
df.loc[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [37]:
df.loc[~(df['age'] < 20)]

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [38]:
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,...,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,...,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,...,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,...,True,C,Southampton,no,False
38,0,3,female,18.0,2,...,False,NaN,Southampton,no,False

In [39]:
mask2 = (titanic.age < 10) & (titanic.sex == "female")
df_female_under10 = titanic.loc[mask2]
df_female_under10.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,...,False,G,Southampton,yes,False
24,0,3,female,8.0,3,...,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,...,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,...,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,...,False,NaN,Southampton,no,False

In [40]:
mask3 = (titanic.age < 10) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3, ['age', 'sex', 'alone']]
df_under10_morethan60.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

In [41]:
df['age_uner_20'] = df['age'] < 20
df.head()

    age     fare  age_uner_20
0  22.0   7.2500        False
1  38.0  71.2833        False
2  26.0   7.9250        False
3  35.0  53.1000        False
4  35.0   8.0500        False

In [42]:
# query() 메소드를 활용한 필터링: DataFrame객체.query(조건 문자열)
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic.loc[0:9, ['age', 'fare']]
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [43]:
df.query('age < 20')

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [44]:
df.query('age >= 20 and fare < 15')

    age     fare
0  22.0   7.2500
2  26.0   7.9250
4  35.0   8.0500
8  27.0  11.1333

In [45]:
df.query('age >= 20 or fare < 15')

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [46]:
# inin() 메서드 활용
# isin() 매서드를 활용한 필터링: DataFrame객체.inin(추출값의 리스트)

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

pd.set_option('display.max_columns', 10)

mask1 = titanic['embark_town'] == "Southampton"
mask2 = titanic['embark_town'] == "Queenstown"
df_boolean = titanic[mask1 | mask2]
df_boolean.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [47]:
isin_filter = titanic['embark_town'].isin(["Southampton", "Queenstown"])
df_isin = titanic[isin_filter]
df_isin.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True